### PR TITLE
yet another quality commit

### PR DESCRIPTION
**Pull request by SevereOverfl0w**
automatically looks up correct ami for region. untested.

### CODE REVIEW

**Comment by jonpither** [comment]
`resolve-service-ami` is not plugged into the preprocessors?

**Comment by SevereOverfl0w** [comment]
Fixed

On 8 Sep 2017 15:30, "Jon Pither" <notifications@github.com> wrote:

resolve-service-ami is not plugged into the preprocessors?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/juxt/roll/pull/10#issuecomment-328118665>, or mute the
thread

**Comment by jonpither** [comment]
change the commit msg and I'll merge ;-)

**Comment by SevereOverfl0w** [comment]
Done

**Comment by jonpither** [comment]
Do we need to have the map stored? Roll could go direct using your code when needed.

**Comment by SevereOverfl0w** [comment]
It could do that, but the http has be async, are you up for an async
rewrite of roll? ;)

**Comment by SevereOverfl0w** [comment]
There's also the added benefit of being able to test an AMI before specifying it for use - it won't change beneath you.

**Pull request merged**
